### ISSUE TITLE
Potential duplicate api call by very careless users

### ISSUE THREAD

**Issue by fanshi1028** [LawsonCheng/poke#49]
If users provided not only a callback, but also called the promise method(should be a quite rare case though), the makeRequest will be called two times, should this be prevented?

**Comment by LawsonCheng** [comment]
promise() has a checking to decide whether makeRequest() is need to execute or not by using the flag `requestFired`.
Will add the same checking mechanism will execute `callback`.

**Comment by LawsonCheng** [comment]
Issue has been resolved, please see pr #52  : )
