### ISSUE TITLE
About EventManager and PokeReturn.

### ISSUE THREAD

**Issue by fanshi1028** [LawsonCheng/poke#65]
1. EventManager.stream.end are called when the http/https request return result when using the EventManager.stream approach, which try to end the stream to consume the result? At which the stream could still be working at that time?

2. Please clarify when the EventManager.end should be called, there is some inconsistency, for example, when using PokeReturn.pipe(the streaming approach) or PokeReturn.promise, EventManager.end is never called, shouldn't it be always be called when the request ended?

3. If I am not mistaken, some error could trigger EventManager.error more than one time, which should be fixed.

4. Registering event callback for event like "error", "data", "end" should not trigger http/https requests imo(which currently it does when the http request is not already fired when attaching callback), in other words, only the below should trigger the request: call the (a)promise method, (b)providing the callback, (c)pipe a stream, (d) set the callback for response event. || only (a), (b), Depends on what you think the api should be.

I could submit a PR later after your clarification.

**Comment by LawsonCheng** [comment]
The issue has been addresses in the latest release. See: #73 #72
