### ISSUE TITLE
Parameter 'input' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by lerichardson** [LawsonCheng/poke#91]
I can't figure this out.
Is it just me? 
I'm using poke on a nodejs/typescript project and anytime I use poke this error returns.
```ts
node_modules/js.poke/src/interfaces/PokeResult.ts:36:29 - error TS7006: Parameter 'input' implicitly has an 'any' type.

36 export function isPokeError(input) : input is PokeError{
                               ~~~~~
```

**Comment by LawsonCheng** [comment]
Hello, this is due to your tsconfig settings. But there is a new release today v1.3.0, you problem should be resolved after the package is upgraded.

**Comment by LawsonCheng** [comment]
> I can't figure this out. Is it just me? I'm using poke on a nodejs/typescript project and anytime I use poke this error returns.
> 
> ```ts
> node_modules/js.poke/src/interfaces/PokeResult.ts:36:29 - error TS7006: Parameter 'input' implicitly has an 'any' type.
> 
> 36 export function isPokeError(input) : input is PokeError{
>                                ~~~~~
> ```

We added explicit type input:PokeError|PokeSuccess, the invalid type `any` problem should be resolved, please upgrade your js.poke to 1.3.0, thank you : )
